-- WITH절을 사용해 자식 대장균의 수를 구한 가상 테이블을 만듦
WITH CHILD_TB AS (
SELECT
    PARENT_ID,
    COUNT(ID) AS 'CHILD_COUNT'
FROM
    ECOLI_DATA
WHERE
    PARENT_ID IS NOT NULL
GROUP BY
    PARENT_ID)
SELECT
    e.ID,
    CASE WHEN c.CHILD_COUNT IS NULL THEN 0
        ELSE c.CHILD_COUNT
        END AS 'CHILD_COUNT'
FROM
    ECOLI_DATA e
LEFT OUTER JOIN
    CHILD_TB c
ON
    e.ID = c.PARENT_ID
ORDER BY
    e.ID ASC;


-- SELF JOIN 하는 방법
SELECT
    e1.ID,
    COUNT(e2.PARENT_ID) AS 'CHILD_COUNT'
FROM
    ECOLI_DATA e1
LEFT JOIN
    ECOLI_DATA e2
ON
    e1.ID = e2.PARENT_ID
GROUP BY
    e1.ID
ORDER BY
    e1.ID ASC;