-- GROUP BY 사용시 SELECT문제 해당 컬럼변수가 없으면 에러남. 주의!

SELECT
    SUM(G.SCORE) AS SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM
    HR_EMPLOYEES E
LEFT JOIN
    HR_GRADE G
ON
    E.EMP_NO = G.EMP_NO
GROUP BY
    E.EMP_NO
ORDER BY
    SCORE DESC
LIMIT 1;