SELECT
    CAR_ID,
    -- DATEDIFF : 단순히 일 차이를 가져올 때 사용, DATEDIFF(날짜1, 날짜2)
    -- TIMESTAMPDIFF : 여러 단위를 사용하여 시간 차이를 구할 때 사용
    ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS 'AVERAGE_DURATION'
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY
    CAR_ID
HAVING
    AVERAGE_DURATION >= 7
ORDER BY
    AVERAGE_DURATION DESC,
    CAR_ID DESC;