SELECT
    E.DEPT_ID,
    D.DEPT_NAME_EN,
    -- 소수첫째자리에서 반올림림
    ROUND(AVG(E.SAL),0) AS AVG_SAL
FROM HR_EMPOYEES E
LEFT JOIN
    HR_DEPARTMENT D
ON
    E.DEPT_ID = D.DEPT_ID
GROUP BY
    E.DEPT_ID
ORDER BY
    AVG_SAL DESC;