SELECT
    ID,
    CASE 
        WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
        # NOT BETEWEEN A AND B : 범위 밖 데이터 조회
        WHEN SIZE_OF_COLONY BETWEEN 101 AND 1000 THEN 'MEDIUM'
        WHEN SIZE_OF_COLONY > 1000 THEN 'HIGH'
    END AS 'SIZE'
FROM
    ECOLI_DATA
ORDER BY
    ID;