SELECT 
    C.YEAR,
    (C.MAX_SIZE-P.SIZE_OF_COLONY) AS YEAR_DEV,
    P.ID
FROM ECOLI_DATA P,
# 연도 별 가장 큰 대장균 크기 서브쿼리
(SELECT
    YEAR(DIFFERENTIATION_DATE) AS 'YEAR',
    MAX(SIZE_OF_COLONY) AS 'MAX_SIZE'
FROM
    ECOLI_DATA
GROUP BY YEAR) C
WHERE YEAR(P.DIFFERENTIATION_DATE) = C.YEAR
ORDER BY C.YEAR, YEAR_DEV;