SELECT
    i.ANIMAL_ID,
    i.NAME
FROM
    ANIMAL_INS i
JOIN
    ANIMAL_OUTS o
ON
    i.ANIMAL_ID = o.ANIMAL_ID
WHERE
    -- ANIMAL_INS의 DATETIME이 ANIMAL_OUTS의 DATETIME보다 큰 값을 조회
    i.DATETIME > o.DATETIME
ORDER BY
    -- ANIMAL_INS의 DATETIME을 기준으로 오름차순
    i.DATETIME ASC;